"""empty message

Revision ID: 0b92343dd539
Revises: 960938b71ae2
Create Date: 2025-12-02 12:56:08.061011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b92343dd539'
down_revision = '960938b71ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('exam_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('course', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('exam_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
