"""empty message

Revision ID: 24f055d35871
Revises: af13d47a8b58
Create Date: 2025-11-13 14:35:48.878509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24f055d35871'
down_revision = 'af13d47a8b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stdid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('cpassword', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=1000), nullable=False))
        batch_op.drop_column('course')
        batch_op.drop_column('cpassword')
        batch_op.drop_column('password')
        batch_op.drop_column('stdid')

    # ### end Alembic commands ###
