"""empty message

Revision ID: fc2527b4b75f
Revises: 24f055d35871
Create Date: 2025-11-13 14:46:43.525731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc2527b4b75f'
down_revision = '24f055d35871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.drop_column('stdid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stdid', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
